// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA31HOzGE0xPa8uVmzBjqb5IRqgoLe7L9E',
    appId: '1:937783707123:web:6c910c9eef6c4c0f3ebe86',
    messagingSenderId: '937783707123',
    projectId: 'dataforgotpass',
    authDomain: 'dataforgotpass.firebaseapp.com',
    storageBucket: 'dataforgotpass.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-FkbZH1EWyIiiVkgeEu7j-uPVXHClFAM',
    appId: '1:937783707123:android:3a39bc086fbe5c163ebe86',
    messagingSenderId: '937783707123',
    projectId: 'dataforgotpass',
    storageBucket: 'dataforgotpass.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBPt-jNR6679TZpUC_ih4Q7yASH8AhAKY',
    appId: '1:937783707123:ios:e54c6b08a2e8c5453ebe86',
    messagingSenderId: '937783707123',
    projectId: 'dataforgotpass',
    storageBucket: 'dataforgotpass.firebasestorage.app',
    iosBundleId: 'com.example.baitaptuan4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBPt-jNR6679TZpUC_ih4Q7yASH8AhAKY',
    appId: '1:937783707123:ios:e54c6b08a2e8c5453ebe86',
    messagingSenderId: '937783707123',
    projectId: 'dataforgotpass',
    storageBucket: 'dataforgotpass.firebasestorage.app',
    iosBundleId: 'com.example.baitaptuan4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA31HOzGE0xPa8uVmzBjqb5IRqgoLe7L9E',
    appId: '1:937783707123:web:ba77821ead3c44663ebe86',
    messagingSenderId: '937783707123',
    projectId: 'dataforgotpass',
    authDomain: 'dataforgotpass.firebaseapp.com',
    storageBucket: 'dataforgotpass.firebasestorage.app',
  );
}
